# server
server:
  port: 10010
  servlet:
    context-path: /wanted

# spring
spring:
  profiles:
    active: h2
  # jpa
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  # sql
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/create-schema.sql
      data-locations: classpath:sql/insert-company.sql,classpath:sql/insert-job-posts.sql,classpath:sql/insert-job-post-ranking.sql
  # security
#  security:
#    user:
#      name: admin
#      password: admin1234

---

# h2 datasource
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    # server mode
#    url: jdbc:h2:tcp://localhost:9092/~/h2/wanted-job-post
    # embedded mode
    url: jdbc:h2:~/h2/wanted-job-post
    username: admin
    password: admin1234
  h2:
    console:
      enabled: true
      path: /h2-console
