DROP TABLE JOB_POSTS;
DROP TABLE COMPANY;

CREATE TABLE COMPANY
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR(255),
    COUNTRY  VARCHAR(50),
    LOCALITY VARCHAR(50),
    REGION   VARCHAR(50),
    CREATED  TIMESTAMP,
    UPDATED  TIMESTAMP
);

CREATE TABLE JOB_POSTS
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_ID BIGINT NOT NULL,
    JOB_TYPE VARCHAR(50),
    COUNTRY VARCHAR(50),
    LOCALITY VARCHAR(50),
    REGION VARCHAR(50),
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
);