DROP TABLE IF EXISTS JOB_POSTS;
DROP TABLE IF EXISTS COMPANY;
DROP TABLE IF EXISTS JOB_POST_RANKING;

CREATE TABLE COMPANY
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL,
    COUNTRY  VARCHAR(50),
    LOCALITY VARCHAR(50),
    REGION   VARCHAR(50),
    CREATED  TIMESTAMP,
    UPDATED  TIMESTAMP
);

CREATE TABLE JOB_POSTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_ID BIGINT NOT NULL,
    JOB_TYPE   VARCHAR(50),
    COUNTRY    VARCHAR(50),
    LOCALITY   VARCHAR(50),
    REGION     VARCHAR(50),
    POSTED     TIMESTAMP,
    CREATED    TIMESTAMP,
    UPDATED    TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID)
);

CREATE TABLE JOB_POST_RANKING
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE    VARCHAR(10) NOT NULL,
    RANKER  VARCHAR(50) NOT NULL,
    COUNT   BIGINT      NOT NULL DEFAULT 0,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP
);
