MERGE INTO JOB_POST_RANKING T
USING (
    SELECT 'COMPANY' AS TYPE, C.NAME AS RANKER, BT.CNT AS COUNT, NOW() AS CREATEDUPDATED
    FROM (SELECT COMPANY_ID, COUNT(1) CNT FROM JOB_POSTS JP GROUP BY COMPANY_ID) BT
    INNER JOIN COMPANY C ON BT.COMPANY_ID = C.ID
)  S ON (T.TYPE = S.TYPE AND T.RANKER = S.RANKER)
WHEN MATCHED THEN
    UPDATE SET T.COUNT = T.COUNT + S.COUNT, T.UPDATED = NOW()
WHEN NOT MATCHED THEN
    INSERT (TYPE, RANKER, COUNT, CREATED)
    VALUES (S.TYPE, S.RANKER, S.COUNT, NOW())
;

MERGE INTO JOB_POST_RANKING T
USING (
    SELECT 'COUNTRY' AS TYPE, COUNTRY AS RANKER, CNT AS COUNT, NOW() AS CREATED
    FROM (SELECT COUNTRY, COUNT(1) CNT FROM JOB_POSTS JP WHERE COUNTRY IS NOT NULL GROUP BY COUNTRY)
)  S ON (T.TYPE = S.TYPE AND T.RANKER = S.RANKER)
WHEN MATCHED THEN
    UPDATE SET T.COUNT = T.COUNT + S.COUNT, T.UPDATED = NOW()
WHEN NOT MATCHED THEN
    INSERT (TYPE, RANKER, COUNT, CREATED)
    VALUES (S.TYPE, S.RANKER, S.COUNT, NOW())
;